# Generated by Django 3.1.2 on 2020-11-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20201025_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Price',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='current_owner',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
