# Generated by Django 3.1.2 on 2020-11-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20201124_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Price',
            new_name='price',
        ),
    ]
