# Generated by Django 3.1.2 on 2020-11-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
