# Generated by Django 3.1.2 on 2020-11-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201129_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='images/agents/'),
        ),
    ]
