# Generated by Django 3.1.2 on 2020-11-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201129_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
